"""
lava: Logging And VAlidation for maggma
"""
__author__ = "Gilberto Pastorello, Dan Gunter"
__copyright__ = "Copyright 2012-2017, The Materials Project"
__version__ = "1.0"
__maintainer__ = "Dan Gunter"
__email__ = "dkgunter@lbl.gov"
__status__ = "Development"
__date__ = "6/14/17"